version: '2.2'
services:
    nginx:
        build: requirements/nginx/
        container_name: nginx
        ports:
            - "443:443"
        restart: always

    wordpress:
        build: requirements/wordpress/
        container_name: wordpress
        ports:
            - '9000:9000'
              #volumes:
         #- ./wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_NAME=wpdb
            - WORDPRESS_TABLE_PREFIX=wp_
            - WORDPRESS_DB_HOST=mysql
            - WORDPRESS_DB_PASSWORD=Strong password
        restart: always
         
