version: '2.2'

networks:
    inception:
        driver: bridge

volumes:
    wp:
        driver: local
        name: wp
        driver_opts:
            type: none
            o: bind
            device: /home/pmailly/data/wordpress

    db:
        driver: local
        name: db
        driver_opts:
            type: none
            o: bind
            device: /home/pmailly/data/mariadb

services:
    nginx:
        build: requirements/nginx/
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - wp:/var/www/html
        networks:
            - inception
        depends_on:
            - wordpress
        restart: always

    wordpress:
        build: requirements/wordpress/
        container_name: wordpress
        environment:
            DB_USER: ${MYSQL_USER}
            DB_PASSWORD: ${MYSQL_PASSWORD}
            WP_ADMIN_USER: ${WP_ADMIN_USER}
            WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
            WP_NORMAL_USER: ${WP_USER}
            WP_NORMAL_PASSWORD: ${WP_PASSWORD}
        ports:
            - '9000:9000'
        volumes:
            - wp:/var/www/html
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - inception
        restart: always

    mariadb:
        build:
            context: requirements/mariadb/
            args:
                DB_USER: ${MYSQL_USER}
                DB_PASSWORD: ${MYSQL_PASSWORD}
                DB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        container_name: mariadb
        volumes:
            - db:/var/lib/mysql
        ports:
            - '3306:3306'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 10s
            retries: 6
        networks:
            - inception
        restart: always
    
