version: '2.2'

networks:
    inception:
        driver: bridge

volumes:
    wp:
        driver: local
        name: wp
        driver_opts:
            type: none
            o: bind
            device: /home/pmailly/data

services:
    nginx:
        build: requirements/nginx/
        container_name: nginx
        ports:
            - "443:443"
        volumes:
            - wp:/var/www/html
        networks:
            - inception
        depends_on:
            - wordpress
        restart: always

    wordpress:
        build: requirements/wordpress/
        container_name: wordpress
        ports:
            - '9000:9000'
        volumes:
            - wp:/var/www/html
        depends_on:
            mariadb:
                condition: service_healthy
        networks:
            - inception
        restart: always

    mariadb:
        build: requirements/mariadb/
        container_name: mariadb
        ports:
            - '3306:3306'
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 10s
            retries: 6
        networks:
            - inception
        restart: always
    
